### ISSUE TITLE
`viur-relations` entities with `src=null` resulting `AssertionError` in `Skeleton.processRemovedRelations`

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#1236]
In a customer project with viur-core 3.5.21, I'm facing this `AssertionError` in the deferred task  `Skeleton.processRemovedRelations` which requires further attention:

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/tasks.py", line 269, in deferred
    _deferred_tasks[funcPath](*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/viur/core/skeleton.py", line 1298, in processRemovedRelations
    assert skel.fromDB(entry["src"].key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

The reason for this is, that the corresponding `viur-relations` entities contain null-keys in the `src`-property. I don't know, why this happens right now.

![image](https://github.com/user-attachments/assets/d446c6ae-3c9c-4282-ae03-0dee094bdf44)

After further investigation, I've found out that the property is null in all cases! This is a general problem that needs to be fixed.

**Comment by phorward** [comment]
Fix by #1237
