### ISSUE TITLE
bug: SkeletonInstance.__init__() got an unexpected keyword argument 'clonedBoneMap'

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#1285]
And, again, one more reason why it's stupid to split a complex software into two packages, that depend on each other.
```
[2024-10-10 22:12:50,406] /.../viur/core/request.py:368 [ERROR] ViUR has caught an unhandled exception!
[2024-10-10 22:12:50,406] /.../viur/core/request.py:369 [ERROR] SkeletonInstance.__init__() got an unexpected keyword argument 'clonedBoneMap'
Traceback (most recent call last):
  File "~/viur-core/viur-core/src/viur/core/request.py", line 343, in _process
    self._route(path)
  File "~/viur-core/viur-core/src/viur/core/request.py", line 602, in _route
    res = caller(*self.args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/viur-core/viur-core/src/viur/core/module.py", line 301, in __call__
    return self._func(self._instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/viur-core/viur-core/src/viur/core/prototypes/list.py", line 216, in list
    return self.render.list(query.fetch())
                            ^^^^^^^^^^^^^
  File "~/myproject/.venv/lib/python3.12/site-packages/viur/datastore/query.py", line 651, in fetch
    skelInstance = conf["SkeletonInstanceRef"](self.srcSkel.skeletonCls, clonedBoneMap=self.srcSkel.boneMap)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SkeletonInstance.__init__() got an unexpected keyword argument 'clonedBoneMap'
```

**Comment by phorward** [comment]
Fixed by  #1286
