### ISSUE TITLE
Commit 0b84619b82fe1ccb366c89fa55d69657516605b3 breaks our local application.

### ISSUE THREAD

**Issue by klaus-thorres** [viur-framework/viur-core#198]
Hey, 

The commit [0b84619b82fe1ccb366c89fa55d69657516605b3](https://github.com/viur-framework/viur-core/commit/0b84619b82fe1ccb366c89fa55d69657516605b3#diff-52507de2df5f0eabe474abbf4ee7964e2800bcb983b999ae42991147d08b8ee1) breaks my system (viur-core-logs below) when running it locally on my Arch Linux machine.

The problem is, that the module cloud, (import in /deploy/viur/core/modules/) does not exist. May I miss something while initializing of the project or the development environment?

```the runtime process for the instance running on port 23908 has unexpectedly quit

[2021-02-12 13:16:29 +0100] [97405] [INFO] Starting gunicorn 20.0.0
[2021-02-12 13:16:29 +0100] [97405] [INFO] Listening at: http://0.0.0.0:23908 (97405)
[2021-02-12 13:16:29 +0100] [97405] [INFO] Using worker: threads
[2021-02-12 13:16:29 +0100] [97408] [INFO] Booting worker with pid: 97408
WARNING  2021-02-12 13:16:30,273 tasks.py:58] Taskqueue disabled, tasks will run inline!
DEBUG    2021-02-12 13:16:30,273 _default.py:180] Checking store_credentials.json for explicit credentials as part of auth process...
[2021-02-12 13:16:30 +0100] [97408] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/workers/base.py", line 133, in init_process
    self.load_wsgi()
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/tmpccI_eR/lib/python3.9/site-packages/gunicorn/util.py", line 331, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<censored>/deploy/main.py", line 28, in <module>
    from viur.core.modules.file import thumbnailer
  File "<censored>/deploy/viur/core/modules/file.py", line 30, in <module>
    from google.cloud import iam_credentials_v1
ImportError: cannot import name 'iam_credentials_v1' from 'google.cloud' (unknown location)
[2021-02-12 13:16:30 +0100] [97408] [INFO] Worker exiting (pid: 97408)
Waiting up to 5 seconds.
DEBUG    2021-02-12 13:16:30,429 requests.py:181] Making request: POST https://oauth2.googleapis.com/token
DEBUG    2021-02-12 13:16:30,430 connectionpool.py:971] Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG    2021-02-12 13:16:30,543 connectionpool.py:452] https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG    2021-02-12 13:16:30,625 background_thread.py:123] Submitted 1 logs
DEBUG    2021-02-12 13:16:30,721 background_thread.py:123] Submitted 2 logs
DEBUG    2021-02-12 13:16:30,721 background_thread.py:160] Background thread exited gracefully.
Sent all pending logs.
[2021-02-12 13:16:30 +0100] [97405] [INFO] Shutting down: Master
[2021-02-12 13:16:30 +0100] [97405] [INFO] Reason: Worker failed to boot.
```

**Comment by sveneberth** [comment]
Hey @klaus-thorres,

I just had the same problem.
After using the same dependencies as in the [base](https://github.com/viur-framework/viur-base/blob/2ec5ada3c1e7e2cbb2dc32724b284aa00bb4668d/deploy/requirements.txt), the core worked again. Check which versions you are using.

Best regards, Sven

**Comment by klaus-thorres** [comment]
Hey @sveneberth,

thanks for the hint. I had to update my local requirements.txt file, so that the needed modules are loaded on startup.

Cheers,
Klaus

**Comment by tsteinruecken** [comment]
Resolved by updating requirements.txt
