### ISSUE TITLE
/{module}/view/structure is broken in json/vi renderer

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#207]
The requests ends in a the 401 Unauthorized.

The problem is the `canView`-method. The passing skeleton is empty/clean. Therefor `skel["key"]` is `None` and is declared as invalid in _buildDBFilter_ of the _KeyBone_ (called from `mergeExternalFilter`).

```sh
ERROR    2021-02-26 18:30:59,117 keyBone.py:100] None could not be converted to bytes
Traceback (most recent call last):
  File "/.../deploy/viur/core/bones/keyBone.py", line 98, in _decodeKey
    return KeyClass.from_legacy_urlsafe(key)
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/datastore/key.py", line 356, in from_legacy_urlsafe
    urlsafe = _to_bytes(urlsafe, encoding="ascii")
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/_helpers.py", line 370, in _to_bytes
    raise TypeError("%r could not be converted to bytes" % (value,))
TypeError: None could not be converted to bytes
WARNING  2021-02-26 18:30:59,120 keyBone.py:101] Could not decode key None
ERROR    2021-02-26 18:30:59,120 db.py:326] 
Traceback (most recent call last):
  File "/.../deploy/viur/core/bones/keyBone.py", line 98, in _decodeKey
    return KeyClass.from_legacy_urlsafe(key)
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/datastore/key.py", line 356, in from_legacy_urlsafe
    urlsafe = _to_bytes(urlsafe, encoding="ascii")
  File "/tmp/tmpfc49Z1/lib/python3.9/site-packages/google/cloud/_helpers.py", line 370, in _to_bytes
    raise TypeError("%r could not be converted to bytes" % (value,))
TypeError: None could not be converted to bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../deploy/viur/core/bones/keyBone.py", line 124, in buildDBFilter
    dbFilter.filter("%s%s =" % (prefix or "", KEY_SPECIAL_PROPERTY), _decodeKey(rawFilter[name]))
  File "/.../deploy/viur/core/bones/keyBone.py", line 102, in _decodeKey
    raise RuntimeError()
RuntimeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../deploy/viur/core/db.py", line 321, in mergeExternalFilter
    bone.buildDBFilter(key, skel, self, filters)
  File "/.../deploy/viur/core/bones/keyBone.py", line 128, in buildDBFilter
    raise RuntimeError()
RuntimeError

```

**Comment by tsteinruecken** [comment]
That's indeed broken. I'd guess the best way here is to construct a query; let it filter by self.listFilter and check wherever at least one entry is returned. This will prevent you from calling /view/structure on an empty module, but you'll get the structure in /add if you have sufficient permissions.
