### ISSUE TITLE
Using of Infilter raises an error (possible bug)

### ISSUE THREAD

**Issue by klaus-thorres** [viur-framework/viur-core#209]
Hi guys :)

I tried to hand over a tuple or list in combination with the IN filter which raises an error.
The query used in the listFilter method of my module is `query.filter("days in", [2 ,3] )`.

By setting the [imit parameter](https://github.com/viur-framework/viur-core/blob/4e5c81a5fb36e08111cb0c4deb438ca69fa601ad/db.py#L696) of the qry.fetch() function call in the _runSingleFilterQuery method of the db.py (line 696) manually to e.g. 5, the IN filter works properly.

May you please provide a solution for this?

```
Traceback (most recent call last):
  File "/home/klaus/coding/ruhrpottmetaller/deploy/viur/core/request.py", line 221, in processRequest
    self.findAndCall(path)
  File "/home/klaus/coding/ruhrpottmetaller/deploy/viur/core/request.py", line 395, in findAndCall
    res = caller(*self.args, **self.kwargs)
  File "/home/klaus/coding/ruhrpottmetaller/deploy/modules/event.py", line 78, in index
    return self.list(*args, **kwargs)
  File "/home/klaus/coding/ruhrpottmetaller/deploy/viur/core/prototypes/list.py", line 169, in list
    res = query.fetch()
  File "/home/klaus/coding/ruhrpottmetaller/deploy/viur/core/db.py", line 877, in fetch
    dbRes = self.run(limit)
  File "/home/klaus/coding/ruhrpottmetaller/deploy/viur/core/db.py", line 826, in run
    res.append(self._runSingleFilterQuery(singleQuery, limit))
  File "/home/klaus/coding/ruhrpottmetaller/deploy/viur/core/db.py", line 697, in _runSingleFilterQuery
    res = next(qryRes.pages)
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/api_core/page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/cloud/datastore/query.py", line 536, in _next_page
    response_pb = self.client._datastore_api.run_query(
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/cloud/datastore_v1/gapic/datastore_client.py", line 383, in run_query
    return self._inner_api_calls["run_query"](
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/tmp/tmpLtdUtG/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 Limit must be non-negative.
```

**Comment by sveneberth** [comment]
This bug is already fixed with #194. The source-code-line 826 quoted in stacktrace confirms that you're using an old version, you have to update the core.

**Comment by klaus-thorres** [comment]
Ok, I updated the source code and now it works as expected. The only flaw is that the version number of google-cloud-logging in the requirements.txt of viur-base has to updated to 2.2.0 as I discovered with @phorward  yesterday evening. Since this is clearly not the business of the core, I am going to make a push request at the right place.

Thank you!

**Comment by sveneberth** [comment]
I have just merged the PR https://github.com/viur-framework/viur-base/pull/33. With this everything should run again and I close this issue.
