### ISSUE TITLE
baseBone-fallback for a recordBone failing with "'NoneType' object is not iterable" when None

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#212]
In this case, the recordBone usage `additional_addresses = recordBone()` produces this error when a fresh, empty skeleton shall be saved.
```
Traceback (most recent call last):
  File "/workspace/viur/core/request.py", line 221, in processRequest
    self.findAndCall(path)
  File "/workspace/viur/core/request.py", line 395, in findAndCall
    res = caller(*self.args, **self.kwargs)
  File "/workspace/modules/user.py", line 162, in login
    assert skel.toDB()
  File "/workspace/skeletons/user.py", line 349, in toDB
    return super().toDB(skel, clearUpdateTag)
  File "/workspace/viur/core/skeleton.py", line 883, in toDB
    key, dbObj, skel, changeList = db.RunInTransaction(txnUpdate, key, skelValues, clearUpdateTag)
  File "/workspace/viur/core/db.py", line 1007, in RunInTransaction
    res = callee(*args, **kwargs)
  File "/workspace/viur/core/skeleton.py", line 695, in txnUpdate
    bone.serialize(skel, key, True)
  File "/workspace/viur/core/bones/bone.py", line 408, in serialize
    for singleValue in newVal:
TypeError: 'NoneType' object is not iterable
```

**Comment by tsteinruecken** [comment]
I thing the error is rather that the defaultValue for recordBones is None (despite it being multiple). We initialize that value in https://github.com/viur-framework/viur-core/blob/master/skeleton.py#L145 . Probably that bug is not limited to recordBones.
