### ISSUE TITLE
Weird UnicodeDecodeError when /file/download is used on file containing umlauts

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#546]
Requesting a file that is stored with the filename **Pendelscharnier - Halbkreis innenbündig.jpg** raises this internal error by gunicorn.
```
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    resp.write(item)
  File "/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 328, in write
    if not isinstance(arg, bytes):
  File "/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 324, in send_headers
    self.headers_sent = True
  File "/lib/python3.10/site-packages/gunicorn/util.py", line 565, in to_bytestring
    return value.encode(encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 1408: ordinal not in range(256)
```
The problem is reproducible both locally or in GAE. It seems that the problem is with the encoding in the header's Content-Disposition.

**Comment by phorward** [comment]
Fixed by #547
