### ISSUE TITLE
AssertionError: Status.ACTIVE (<enum 'Status'>) is not supported

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/viur-core#701]
ViUR-core3.4.0b2
```
[2023-04-04 19:18:34,017] /.../core/modules/user.py:978 [ERROR] Status.ACTIVE (<enum 'Status'>) is not supported
Traceback (most recent call last):
  File "project/lib/python3.10/site-packages/viur/core/modules/user.py", line 975, in createNewUserIfNotExists
    addSkel.toDB()
  File "project/lib/python3.10/site-packages/viur/core/skeleton.py", line 1021, in toDB
    key, dbObj, skel, changeList = db.RunInTransaction(txnUpdate, key, skelValues)
  File "src/viur/datastore/transport.pyx", line 782, in viur.datastore.transport.RunInTransaction
  File "src/viur/datastore/transport.pyx", line 779, in viur.datastore.transport.RunInTransaction
  File "project/lib/python3.10/site-packages/viur/core/skeleton.py", line 975, in txnUpdate
    db.Put(dbObj)
  File "src/viur/datastore/transport.pyx", line 700, in viur.datastore.transport.Put
  File "src/viur/datastore/transport.pyx", line 209, in viur.datastore.transport.pythonPropToJson
  File "src/viur/datastore/transport.pyx", line 239, in viur.datastore.transport.pythonPropToJson
AssertionError: Status.ACTIVE (<enum 'Status'>) is not supported
```

**Comment by phorward** [comment]
Hello, after a detailed exploration, I've found out that this problem has to deal with a project-specific problem. It's not a bug with viur-core.

**Comment by sveneberth** [comment]
> Hello, after a detailed exploration, I've found out that this problem has to deal with a project-specific problem. It's not a bug with viur-core.

Okay, that's what I assumed.
I was not able to reproduce the error. Neither within a StartupTask, nor in a normal request. No problem both in the cloud and locally.

Thanks for the clarification
