### ISSUE TITLE
Invalid Mime-type? Cannot upload customers files with new core

### ISSUE THREAD

**Issue by xnopasaranx** [viur-framework/viur-core#727]
The file I was trying to upload was downloaded from a viur2 production system, it is an *.oft file. I don't know what the correct mimetype should be here, but I doubt that we are doing everything correctly when checking. Why do we check the mimetype at all? Do we reject any type of file or is this just for the mimetype field?

```
[2023-04-27 13:44:13,608] /.../viur/core/request.py:299 [ERROR] ViUR has caught an unhandled exception!
[2023-04-27 13:44:13,608] /.../viur/core/request.py:300 [ERROR] Invalid Mime-Type
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project-viur3-5lETOfwa/lib/python3.10/site-packages/viur/core/request.py", line 275, in processRequest
    self.findAndCall(path)
  File "/home/user/.local/share/virtualenvs/project-viur3-5lETOfwa/lib/python3.10/site-packages/viur/core/request.py", line 623, in findAndCall
    res = caller(*newArgs, **newKwargs)
  File "/home/user/.local/share/virtualenvs/project-viur3-5lETOfwa/lib/python3.10/site-packages/viur/core/modules/file.py", line 520, in getUploadURL
    assert len(mimeType.split("/")) == 2, "Invalid Mime-Type"
AssertionError: Invalid Mime-Type
[2023-04-27 13:44:13] [500] [POST] /json/file/getUploadURL
```

**Comment by xnopasaranx** [comment]
If someone wants to take a look at the file in question, message me and I will provide the file. Obviously not on github and only for internal usage.

**Comment by xnopasaranx** [comment]
I took some time to check this locally and the mimeType variable that is being checked returns an empty string for some reason. Using unix file to check the mimetype returns "application/vnd.ms-outlook" and trying the assertions on that string works as expected. It seems that the mimetype cannot be read at all for some reason.

**Comment by xnopasaranx** [comment]
Okay, it appears that the core is not at fault here. This is a bug in the new vue vi... it should pass the mimetype as a string to getUploadURL, but in this case it's an empty string so the assertions fail. I will close this issue now and open a new one in the correct place.

**Comment by phorward** [comment]
Okay as #743 is now merged, this issue can be closed.
