### ISSUE TITLE
Cloning a SkeletonInstance with data stored into a relationalBone fails

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#78]
This works:
```python
# This works
skel = FeedSkel().clone()
skel = skel.clone()

# This works also
skel = FeedSkel().clone()
skel.setBoneValue("name", "Hello World")
skel = skel.clone()
```
But this does not work:
```python
skel = FeedSkel().clone()
skel.setBoneValue("feedlist", "aglteVByb2plY3RyFQsSCGZlZWRsaXN0GICAgNiGpYMKDA")
skel = skel.clone()
```
and fails with the following backtrace:
```
ERROR    2020-07-21 16:36:01,245 request.py:245] Viur caught an unhandled exception!
ERROR    2020-07-21 16:36:01,245 request.py:246] '__deepcopy__'
Traceback (most recent call last):
  File "~/myProject/deploy/viur/core/request.py", line 218, in processRequest
    self.findAndCall(path)
  File "~/myProject/deploy/viur/core/request.py", line 392, in findAndCall
    res = caller(*self.args, **self.kwargs)
  File "~/myProject/deploy/modules/index.py", line 21, in test
    skel = skel.clone()
  File "~/myProject/deploy/viur/core/skeleton.py", line 184, in clone
    res.accessedValues = copy.deepcopy(self.accessedValues)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 151, in deepcopy
    copier = getattr(x, "__deepcopy__", None)
  File "~/myProject/deploy/viur/core/skeleton.py", line 161, in __getattr__
    return self.boneMap[item]
KeyError: '__deepcopy__'
```

**Comment by phorward** [comment]
5e4c771 seems to fix this. Can you please integrate it then?
