### ISSUE TITLE
bug: `findBoundTask` seems to call with a `Skeleton`?

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#907]
This error happens with viur-core==3.3.5, and should be analyzed.
```
'__dict__'
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/request.py", line 276, in processRequest
    self.findAndCall(path)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/request.py", line 636, in findAndCall
    res = caller(*newArgs, **newKwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/tasks.py", line 309, in cron
    res = self.findBoundTask(task)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/tasks.py", line 185, in findBoundTask
    res = self.findBoundTask(task, v, depth + 1)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/tasks.py", line 185, in findBoundTask
    res = self.findBoundTask(task, v, depth + 1)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/tasks.py", line 185, in findBoundTask
    res = self.findBoundTask(task, v, depth + 1)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/tasks.py", line 175, in findBoundTask
    for attr in dir(obj):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/viur/core/skeleton.py", line 217, in __getattr__
    return self.boneMap[item]
KeyError: '__dict__'
```

**Comment by sveneberth** [comment]
To be sure: Only with `viur-core==3.3.5` or since `viur-core>=3.3.5`?

**Comment by phorward** [comment]
> To be sure: Only with `viur-core==3.3.5` or since `viur-core>=3.3.5`?

Not tested, yet.
