### ISSUE TITLE
defaultValue is not handled as expected

### ISSUE THREAD

**Issue by phorward** [viur-framework/viur-core#95]
Hello there,

this issue relates to two different problems relating defaultValue on bones.

1. ~~I want to set a relationalBone's defaultValue using a callable, which returns either None or a valid key. Pull request #94 resolves the issue for my case, but I'm sure that its not satisfying ViUR's concept.~~ FIXED AND REPLACED BY #97 
2. When I instanciate a skeleton, the defaultValues are not pre-filled as expected. I tried to handle this case by adding a function 
```python
	def initialize(self):
		"""
		Initialize this instance with all its default values.
		"""
		for key, bone in self.boneMap.items():
			defaultValue = bone.getDefaultValue()
			if defaultValue is not None:
				self.accessedValues[key] = defaultValue

		return self
```
directly to skeleton.SkeletonInstance.

A call would look like so:
```python
	def addSkel(self):
		skel = super().addSkel().clone().initialize()
		...
```

It curiously works, and the entity is also saved, but I'm getting an error 500 anyway with  this content:
```
ERROR    2020-08-04 23:48:46,137 request.py:245] Viur caught an unhandled exception!
ERROR    2020-08-04 23:48:46,139 request.py:246] 400 At most 20 nested array/entity values are supported.
Traceback (most recent call last):
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "At most 20 nested array/entity values are supported."
        debug_error_string = "{"created":"@1596577726.137116011","description":"Error received from peer ipv4:172.217.22.106:443","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"At most 20 nested array/entity values are supported.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/MyProject/deploy/viur/core/request.py", line 218, in processRequest
    self.findAndCall(path)
  File "~/MyProject/deploy/viur/core/request.py", line 392, in findAndCall
    res = caller(*self.args, **self.kwargs)
  File "~/MyProject/deploy/viur/core/prototypes/list.py", line 256, in add
    self.onAdded(skel)
  File "~/MyProject/deploy/modules/chatmessage.py", line 59, in onAdded
    conf["viur.mainApp"].chatthread.updateCache(
  File "~/MyProject/deploy/modules/chatthread.py", line 73, in updateCache
    db.RunInTransaction(txn)
  File "~/MyProject/deploy/viur/core/db.py", line 920, in RunInTransaction
    res = callee(*args, **kwargs)
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/cloud/datastore/batch.py", line 302, in __exit__
    self.commit()
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/cloud/datastore/transaction.py", line 241, in commit
    super(Transaction, self).commit()
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/cloud/datastore/batch.py", line 274, in commit
    self._commit()
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/cloud/datastore/batch.py", line 249, in _commit
    commit_response_pb = self._client._datastore_api.commit(
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/cloud/datastore_v1/gapic/datastore_client.py", line 570, in commit
    return self._inner_api_calls["commit"](
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/tmp/tmpjDioH2/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 At most 20 nested array/entity values are supported.
```

I need a valid, ViUR-compatible solution for boths cases, because they partly stick together.

**Comment by tsteinruecken** [comment]
Should be fixed by #81 - can you confirm if this is resolved? @phorward
