### ISSUE TITLE
deprecation handling in `utils` caused `AttributeError`

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/viur-core#999]
I have an old `utils.sendEMail()` call. 

This resulted in this error:

```py
[2023-12-18 15:38:13,170] /.../viur/core/request.py:424 [ERROR] Deferred Task emulation <function XXX.do_import at 0x7f5592fba160> failed
Traceback (most recent call last):
  File ".../lib/python3.11/site-packages/viur/core/request.py", line 422, in _process
    task()
  File ".../lib/python3.11/site-packages/viur/core/tasks.py", line 512, in task
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/viur/core/tasks.py", line 416, in inner_wrapper
    raise exc
  File ".../lib/python3.11/site-packages/viur/core/tasks.py", line 407, in inner_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/.../deploy/modules/xxx.py", line 1610, in do_import
    utils.sendEMail(
    ^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/viur/core/utils.py", line 355, in __getattr__
    return super(__import__(__name__).__class__).__getattr__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute '__getattr__'
```

**Comment by phorward** [comment]
I think this got fixed by #1065 ?
